### ISSUE TITLE
Error importing template

### ISSUE THREAD

**Issue by speedlight** [rvalitov/zabbix-php-fpm#1]
First thanks for the template!

I'm trying to importing the XML file into Templates but I'm getting `Incorrect file upload.` message. 
I look into zabbix_server.log but nothing appears at the moment of the import. What can I do to troubleshoot this? Cheers

```sh
OS: Debian 9
PHP: 7.0.33
Zabbix server: 4.2.5
```

**Comment by rvalitov** [comment]
Hi! Your environment is perfectly compatible with this template. To view the import errors, please click the "Details" section in the Zabbix GUI. It should be on the same import page near the error message. I saw this solution for earlier Zabbix version [here](https://www.zabbix.com/forum/zabbix-troubleshooting-and-problems/35436-how-to-troubleshoot-template-import-failure), but I think it should work with modern Zabbix too.
![image](https://user-images.githubusercontent.com/16267156/63744975-a84a9880-c8a9-11e9-9fd9-f4575f17453d.png)

**Comment by helders** [comment]
Yes i did change the AllowRoot setting on the conf file. On the Discovery Rule page of the hosts it says Unsuported item key.

**Comment by rvalitov** [comment]
Try to run the discovery script manually, and write here its output. Run the command below:
```bash
bash zabbix_php_fpm_discovery.sh
```

The output should be similar to this:
```
{"data":[{"{#POOLNAME}":"web1"
,"{#POOLSOCKET}":"/var/lib/php7.3-fpm/web1.sock"
},{"{#POOLNAME}":"web4"
,"{#POOLSOCKET}":"/var/lib/php7.3-fpm/web4.sock"
},{"{#POOLNAME}":"www"
,"{#POOLSOCKET}":"/run/php/php7.3-fpm.sock"
}]}
```

**Comment by helders** [comment]
Here it is:

{"data":[{"{#POOLNAME}":"web1"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web1.sock"
},{"{#POOLNAME}":"web102"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web102.sock"
},{"{#POOLNAME}":"web103"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web103.sock"
},{"{#POOLNAME}":"web109"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web109.sock"
},{"{#POOLNAME}":"web17"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web17.sock"
},{"{#POOLNAME}":"web18"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web18.sock"
},{"{#POOLNAME}":"web22"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web22.sock"
},{"{#POOLNAME}":"web3"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web3.sock"
},{"{#POOLNAME}":"web4"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web4.sock"
},{"{#POOLNAME}":"web5"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web5.sock"
},{"{#POOLNAME}":"web84"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web84.sock"
},{"{#POOLNAME}":"web94"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web94.sock"
},{"{#POOLNAME}":"web95"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web95.sock"
},{"{#POOLNAME}":"web97"
,"{#POOLSOCKET}":"/var/lib/php5-fpm/web97.sock"
},]}

i noticed there is a comma followed by no data, i think that's the issue

**Comment by rvalitov** [comment]
@helders sorry for a late reply, I updated the zabbix_php_fpm_discovery.sh file, please try to run it again, now it should display all items without the last comma.
