### ISSUE TITLE
grep of processes is not exact

### ISSUE THREAD

**Issue by pbousek** [rvalitov/zabbix-php-fpm#10]
hello, maybe i found a bug:

if you have two pools

lets say
- default
- default2

and you use grep of poolname from running processes, it's not exact ... because both names  are valid in the first case (default)

Petr

**Comment by rvalitov** [comment]
Hi! Did you test the discovery script? Does it find all the pools?

**Comment by pbousek** [comment]
sure, but it shows same port for both default and defualt2 pools although it is not

**Comment by rvalitov** [comment]
Can you please post here a complete output of command `ps ax | grep "php-fpm: pool "`?

**Comment by rvalitov** [comment]
In my case I use sockets and all pools have names webXX, where XX is a number. That works fine. So, I'm waiting for your test case. May be it's related to the IP detection.

**Comment by pbousek** [comment]
ps ax | grep "php-fpm: pool "
 5770 ?        S      0:00 php-fpm: pool default56
 5771 ?        S      0:00 php-fpm: pool default56
 5773 ?        S      0:00 php-fpm: pool default56
 5774 ?        S      0:00 php-fpm: pool default56
 5775 ?        S      0:00 php-fpm: pool default56
 5776 ?        S      0:00 php-fpm: pool default56
 5777 ?        S      0:00 php-fpm: pool default56
 5778 ?        S      0:00 php-fpm: pool default56
 5779 ?        S      0:00 php-fpm: pool default56
 5780 ?        S      0:00 php-fpm: pool default56
 5782 ?        S      0:00 php-fpm: pool wudy
 5783 ?        S      0:00 php-fpm: pool wudy
 5784 ?        S      0:00 php-fpm: pool wudy
 5785 ?        S      0:00 php-fpm: pool wudy
 5786 ?        S      0:00 php-fpm: pool wudy
 5787 ?        S      0:00 php-fpm: pool wudy
 5789 ?        S      0:00 php-fpm: pool wudy
 5790 ?        S      0:00 php-fpm: pool wudy
 5791 ?        S      0:00 php-fpm: pool wudy
 5792 ?        S      0:00 php-fpm: pool wudy
 5862 ?        S      0:00 php-fpm: pool b3da
 5863 ?        S      0:01 php-fpm: pool b3da
 5864 ?        S      0:01 php-fpm: pool b3da
 5865 ?        S      0:00 php-fpm: pool b3da
 5866 ?        S      0:00 php-fpm: pool b3da
 5867 ?        S      0:00 php-fpm: pool b3da
 5868 ?        S      0:01 php-fpm: pool b3da
 5869 ?        S      0:00 php-fpm: pool b3da
 5870 ?        S      0:00 php-fpm: pool b3da
 5871 ?        S      0:00 php-fpm: pool b3da
 5872 ?        S      0:00 php-fpm: pool butiko
 5873 ?        S      0:00 php-fpm: pool butiko
 5874 ?        S      0:00 php-fpm: pool butiko
 5875 ?        S      0:00 php-fpm: pool butiko
 5876 ?        S      0:00 php-fpm: pool butiko
 5877 ?        S      0:00 php-fpm: pool butiko
 5878 ?        S      0:00 php-fpm: pool butiko
 5879 ?        S      0:00 php-fpm: pool butiko
 5880 ?        S      0:00 php-fpm: pool butiko
 5881 ?        S      0:00 php-fpm: pool butiko
 5882 ?        S      0:02 php-fpm: pool chillidoc
 5883 ?        S      0:01 php-fpm: pool chillidoc
 5884 ?        S      0:02 php-fpm: pool chillidoc
 5885 ?        S      0:02 php-fpm: pool chillidoc
 5886 ?        S      0:01 php-fpm: pool chillidoc
 5887 ?        S      0:02 php-fpm: pool chillidoc
 5888 ?        S      0:02 php-fpm: pool chillidoc
 5889 ?        S      0:01 php-fpm: pool chillidoc
 5890 ?        S      0:02 php-fpm: pool chillidoc
 5891 ?        S      0:02 php-fpm: pool chillidoc
 5892 ?        S      0:00 php-fpm: pool curia
 5893 ?        S      0:00 php-fpm: pool curia
 5894 ?        S      0:00 php-fpm: pool curia
 5895 ?        S      0:00 php-fpm: pool curia
 5896 ?        S      0:00 php-fpm: pool curia
 5897 ?        S      0:02 php-fpm: pool default
 5898 ?        S      0:02 php-fpm: pool default
 5899 ?        S      0:02 php-fpm: pool default
 5900 ?        S      0:01 php-fpm: pool default
 5901 ?        S      0:01 php-fpm: pool default
 5902 ?        S      0:02 php-fpm: pool default
 5903 ?        S      0:01 php-fpm: pool default
 5904 ?        S      0:02 php-fpm: pool default
 5905 ?        S      0:02 php-fpm: pool default
 5906 ?        S      0:02 php-fpm: pool default
 5907 ?        S      0:00 php-fpm: pool floor
 5908 ?        S      0:00 php-fpm: pool floor
 5909 ?        S      0:00 php-fpm: pool floor
 5910 ?        S      0:00 php-fpm: pool floor
 5911 ?        S      0:00 php-fpm: pool floor
 5912 ?        S      0:00 php-fpm: pool floor
 5913 ?        S      0:00 php-fpm: pool floor
 5914 ?        S      0:00 php-fpm: pool floor
 5915 ?        S      0:00 php-fpm: pool floor
 5916 ?        S      0:00 php-fpm: pool floor
 5917 ?        S      0:00 php-fpm: pool kamenodnas
 5918 ?        S      0:00 php-fpm: pool kamenodnas
 5919 ?        S      0:00 php-fpm: pool kamenodnas
 5920 ?        S      0:00 php-fpm: pool kamenodnas
 5921 ?        S      0:00 php-fpm: pool kamenodnas
 5922 ?        S      0:00 php-fpm: pool kamenodnas
 5923 ?        S      0:00 php-fpm: pool kamenodnas
 5924 ?        S      0:00 php-fpm: pool kamenodnas
 5925 ?        S      0:00 php-fpm: pool kamenodnas
 5926 ?        S      0:00 php-fpm: pool kamenodnas
 5928 ?        S      0:04 php-fpm: pool kopiluwak
 5929 ?        S      0:05 php-fpm: pool kopiluwak
 5930 ?        S      0:04 php-fpm: pool kopiluwak
 5931 ?        S      0:04 php-fpm: pool kopiluwak
 5932 ?        S      0:04 php-fpm: pool kopiluwak
 5933 ?        S      0:04 php-fpm: pool kopiluwak
 5934 ?        S      0:04 php-fpm: pool kopiluwak
 5936 ?        S      0:04 php-fpm: pool kopiluwak
 5937 ?        S      0:06 php-fpm: pool kopiluwak
 5938 ?        S      0:00 php-fpm: pool wudyeu
 5939 ?        S      0:00 php-fpm: pool wudyeu
 5941 ?        S      0:00 php-fpm: pool wudyeu
 5942 ?        S      0:00 php-fpm: pool wudyeu
 5943 ?        S      0:00 php-fpm: pool wudyeu
 5944 ?        S      0:00 php-fpm: pool wudyeu
 5945 ?        S      0:00 php-fpm: pool wudyeu
 5946 ?        S      0:00 php-fpm: pool wudyeu
 5947 ?        S      0:00 php-fpm: pool wudyeu
 5949 ?        S      0:00 php-fpm: pool wudyeu
 5950 ?        S      0:00 php-fpm: pool zbraneb
 5951 ?        S      0:00 php-fpm: pool zbraneb
 5952 ?        S      0:00 php-fpm: pool zbraneb
 5953 ?        S      0:00 php-fpm: pool zbraneb
 5954 ?        S      0:00 php-fpm: pool zbraneb
 5955 ?        S      0:00 php-fpm: pool zbraneb
 5956 ?        S      0:00 php-fpm: pool zbraneb
 5957 ?        S      0:00 php-fpm: pool zbraneb
 5958 ?        S      0:00 php-fpm: pool zbraneb
 5959 ?        S      0:00 php-fpm: pool zbraneb
10331 ?        S      0:03 php-fpm: pool kopiluwak
17315 pts/1    R+     0:00 grep php-fpm: pool

**Comment by pbousek** [comment]
I found a solution
change
POOL_PID=`printf '%s\n' "${PS_LIST[@]}" | $S_GREP "php-fpm: pool $line" | $S_HEAD -1 | $S_AWK '{print $1}'`

to

POOL_PID=`printf '%s\n' "${PS_LIST[@]}" | $S_GREP "php-fpm: pool $line$" | $S_HEAD -1 | $S_AWK '{print $1}'`

use "$" in grep as end of line after $line

**Comment by rvalitov** [comment]
@pbousek thank you very much! Would you like to make a pull request yourself?

**Comment by pbousek** [comment]
@rvalitov no, thank you
