### ISSUE TITLE
wrong php pool discovery

### ISSUE THREAD

**Issue by pbousek** [rvalitov/zabbix-php-fpm#18]
@rvalitov maybe there is another bug, i found that triggers are somehow multiplicated, but don't know why - after localhost:port value has changed for discovery rule, new item/triggers are added

![image](https://user-images.githubusercontent.com/21953786/71727479-a8037080-2e3a-11ea-8510-35a54f032b2e.png)

here is the problem
```
root@api1:/etc/zabbix# lsof -p 26838 |grep -e unix -e TCP 
php-fpm7. 26838 www-data    9u  IPv4 224352639      0t0       TCP localhost:8001 (LISTEN)
root@api1:/etc/zabbix# lsof -p 26838 |grep -e unix -e TCP 
php-fpm7. 26838 www-data    9u  IPv4 224352639      0t0       TCP localhost:8001 (LISTEN)
root@api1:/etc/zabbix# lsof -p 26838 |grep -e unix -e TCP 
php-fpm7. 26838 www-data    9u  IPv4 224352639      0t0       TCP localhost:8001 (LISTEN)
root@api1:/etc/zabbix# lsof -p 26838 |grep -e unix -e TCP 
php-fpm7. 26838 www-data    4u  IPv4 324700387      0t0       TCP localhost:8001->localhost:51786 (ESTABLISHED)
php-fpm7. 26838 www-data    9u  IPv4 224352639      0t0       TCP localhost:8001 (LISTEN)
```

you get the first value - that only say that php process has established connection from 8001 -> 51786

but you should work with the LISTEN line

**Comment by pbousek** [comment]
sorry, it seems OK, after some more analysis, this is some old discovered data (expiration of discovered data are 30 days) so it will take next few days till it disappear  ... last version of discovery seems ok, all those item were found before

**Comment by rvalitov** [comment]
Thank you! Just for info. The latest version of the script now supports the "debug" mode to easier investigate all the steps of the discovery script, just add the `debug` keyword at the end:

```console
bash /etc/zabbix/zabbix_php_fpm_discovery.sh debug
```

I close this issue then.
