### ISSUE TITLE
Doubled items for pools

### ISSUE THREAD

**Issue by pbousek** [rvalitov/zabbix-php-fpm#21]
hello @rvalitov, maybe this is not issue, but please why are the items displayed twice:
first - they are all together across all pools  with number of CPUs and pool <name> status

and second they are displayed again per pool - same data (without those two mentioned above)
![image](https://user-images.githubusercontent.com/21953786/72845827-b4435680-3c9f-11ea-81d3-4acc05246269.png)

**Comment by pbousek** [comment]
when you have 10 or more pools its about 170 doubled items...

**Comment by rvalitov** [comment]
Hi! Actually it's not a bug. It's the way Zabbix displays information. But it has lots of grouping and filtering options that you can use. For example, click select:
![image](https://user-images.githubusercontent.com/16267156/72885081-49823180-3d18-11ea-903c-ba58580d51ec.png)
Then choose data that you need:
![image](https://user-images.githubusercontent.com/16267156/72885095-53a43000-3d18-11ea-9b08-1fe097c91c21.png)
You can choose to display all PHP-FPM pools at once (choose PHP-FPM), or you can select individual pool. Doing this way you will not see any doubled items.

**Comment by rvalitov** [comment]
I documented this case in the newly available [Wiki section](https://github.com/rvalitov/zabbix-php-fpm/wiki/Testing-and-Troubleshooting). I hope it will be useful for other users to avoid any misunderstanding.
