### ISSUE TITLE
feature request - trigger when "max children reached"

### ISSUE THREAD

**Issue by pbousek** [rvalitov/zabbix-php-fpm#28]
Hello @rvalitov, just idea... it will be nice when I will be noticed when some pool reached max children settings and it's time to solve it somehow.. for example increase it.
But it seems that there isn't currently any such trigger. 

What do you think?

Thanks
Petr

**Comment by rvalitov** [comment]
Hi! Thank you for this idea. I don't know why, but I always have been thinking, that reaching max children is a normal situation that does not necessarily mean anything bad. Besides, the logic here may depend on the process manager type. I didn't find any official info or any test data that will prove or disprove my idea. I'm afraid that simply adding an alert warning message will not be informative and can lead to messages spam (when max children reached can be triggered multiple times per minute). I will appreciate if we can discuss this topic further, and you can share some links to any documentation, test cases or share your own experience. Thank you!

**Comment by rvalitov** [comment]
Some more info to consider:

- `max children reached` situation may be reported by PHP in the PHP log [link](https://community.webcore.cloud/tutorials/how_to_solve_php_fpm_server_reached_max_children/)
- `max children reached` may lead to slow website speed or "website down" errors [link](https://support.plesk.com/hc/en-us/articles/214528405-Websites-on-PHP-FPM-are-unavailable-or-loading-slowly-server-reached-max-children-setting-OR-pool-seems-busy-)
- raising `max children` may not easily solve this problem [link](https://www.digitalocean.com/community/questions/php5-fpm-crashing-server-reached-pm-max_children-setting-ubuntu-14-lemp)
- increasing `max children` may significantly increase the amount of used RAM by PHP, so it should be set carefully, especially in cases when you have multiple pools that running together may lead to "out of memory" situation for the server.
