### ISSUE TITLE
Alternative PHP

### ISSUE THREAD

**Issue by fox-se** [rvalitov/zabbix-php-fpm#29]
Здравствуйте
Есть VPS с установленными: Zabbix 4.4.6, ISPmanager
Подключил в панели дополнительно : Альтернативная версия PHP 7.3 |   | PHP 7.3 CGI, PHP 7.3 PHP-FPM

По основному PHP все данные вашего шаблона отображаются, по альтернативному только:
 CPU avg utilization, CPU utilization, memory used, memory utilization.
По остальным Item ничего.

Конфиги (права, владелец - root):

работающего
[zabbix]
user = apache
group = apache
listen = /run/php-fpm/zabbix.sock
listen.owner = nginx
listen.allowed_clients = 127.0.0.1
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
php_value[session.save_handler] = files
php_value[session.save_path]    = /var/lib/php/session
php_value[max_execution_time] = 300
php_value[memory_limit] = 128M
php_value[post_max_size] = 16M
php_value[upload_max_filesize] = 2M
php_value[max_input_time] = 300
php_value[max_input_vars] = 10000
pm.status_path = /php-fpm-status

неработающий
[user_isp]
pm = dynamic
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_children = 5
pm.max_spare_servers = 5
php_admin_value[display_errors] = stderr
php_admin_value[log_errors] = On
listen = /var/www/php-fpm/user_isp.sock
listen.mode = 0660
listen.owner = user_isp
listen.group = apache
user = user_isp
group = user_isp
chdir = /
pm.status_path = /php-fpm-status

Что можно сделать, куда смотреть?

**Comment by ttsrg** [comment]
Если там ключ [php-fpm] меняйте на  [php-fpm7.3]

**Comment by rvalitov** [comment]
Здравствуйте!
Спасибо большое за информацию. Действительно, там ключ `php-fpm`. Соответственно, команда `ps ax` ищет по этому ключу. Перед изменением скрипта я бы хотел воспроизвести у себя эту ошибку. Скажите пожалуйста, какая у Вас ОС и версия? Альтернативный PHP каким образом ставился: из каких-то готовых пакетов или сборки или как-то иначе?

**Comment by fox-se** [comment]
Здравствуйте!
Спасибо за ответ.
Centos 7

/etc/zabbix/zabbix_agentd.conf
AllowRoot=1
User=root

/etc/systemd/system/zabbix-agent.service.d/override.conf
[Service]
User=root
Group=root

# systemctl daemon-reload
# systemctl restart zabbix-agent

Работает !

[root@ssssss ~]# ps aux | grep "php"
root       910  0.0  0.5 363536 11072 ?        Ss   Apr11   0:11 php-fpm: master process (/etc/php-fpm.conf)
apache    1034  0.2  0.9 370868 18396 ?        S    Apr11  10:14 php-fpm: pool www
apache    1035  0.2  1.4 379076 26544 ?        S    Apr11   9:55 php-fpm: pool www
apache    1036  0.2  1.0 372640 19968 ?        S    Apr11  10:11 php-fpm: pool www
apache    1037  0.2  0.9 370620 18028 ?        S    Apr11  10:03 php-fpm: pool www
apache    1038  0.2  1.3 377300 24776 ?        S    Apr11   9:45 php-fpm: pool www
apache    1039  0.0  0.3 363128  6548 ?        S    Apr11   0:00 php-fpm: pool apache
apache    1040  0.0  0.3 363308  6552 ?        S    Apr11   0:00 php-fpm: pool zabbix
apache    1041  0.0  0.3 363308  6552 ?        S    Apr11   0:00 php-fpm: pool zabbix
apache    1042  0.0  0.3 363308  6552 ?        S    Apr11   0:00 php-fpm: pool zabbix
apache    1043  0.0  0.3 363308  6548 ?        S    Apr11   0:00 php-fpm: pool zabbix
apache    1044  0.0  0.3 363308  6548 ?        S    Apr11   0:00 php-fpm: pool zabbix
apache    1884  0.2  0.9 370348 17688 ?        S    Apr11  10:08 php-fpm: pool www
apache    4015  0.2  1.2 375484 22760 ?        S    Apr12   7:18 php-fpm: pool www
apache    4017  0.2  1.1 373736 21084 ?        S    Apr11   9:54 php-fpm: pool www
root      7064  0.0  0.0 112716   960 pts/0    S+   17:25   0:00 grep --color=auto php
apache   15511  0.0  0.3 363308  6548 ?        S    Apr13   0:00 php-fpm: pool zabbix
apache   19589  0.0  0.3 363128  6548 ?        S    Apr12   0:00 php-fpm: pool apache
apache   21434  0.3  0.8 369304 16576 ?        S    Apr13   5:08 php-fpm: pool www
root     28531  0.0  0.8 464764 15268 ?        Ss   17:15   0:00 php-fpm: master process (/opt/php73/etc/php-fpm.conf)
xxxxx-s+ 28533  0.1  2.0 475816 37960 ?        S    17:15   0:00 php-fpm: pool xxxxx-site
yyyyy-+ 28534  0.1  2.3 474036 43440 ?        S    17:15   0:01 php-fpm: pool yyyyy-site
zzzz-si+ 28535  0.3  2.3 474260 43628 ?        S    17:15   0:01 php-fpm: pool zzzz-site
uuuuuu 28536  0.0  0.3 464740  6420 ?        S    17:15   0:00 php-fpm: pool uuuuuu
yyyyy-+ 29083  0.1  1.4 467784 27200 ?        S    17:15   0:00 php-fpm: pool yyyyy-site
zzzz-si+ 29304  0.1  1.8 474264 34040 ?        S    17:15   0:01 php-fpm: pool zzzz-site
xxxxx-s+ 31038  0.0  1.3 467624 24492 ?        S    17:17   0:00 php-fpm: pool xxxxx-site

**Comment by fox-se** [comment]
Вариант сделать zabbix-agent не-ROOT возможен?

**Comment by rvalitov** [comment]
Спасибо за информацию. На первый взгляд вывод `ps` вписывается в работу скрипта.
Вы пробовали решать проблему по шагам, как описано в вики? https://github.com/rvalitov/zabbix-php-fpm/wiki/Testing-and-Troubleshooting#2-the-template-does-not-work

Я так понимаю что пул автоопределяется, поэтому вероятно вы можете сразу приступить к этому пункту https://github.com/rvalitov/zabbix-php-fpm/wiki/Testing-and-Troubleshooting#2-get-status-of-required-pool

Сообщите о результатах.

**Comment by rvalitov** [comment]
> Вариант сделать zabbix-agent не-ROOT возможен?

Конечно, это тоже описано в вики https://github.com/rvalitov/zabbix-php-fpm/wiki/Installation#132-method-2-grant-privileges-to-the-php-fpm-auto-discovery-script-only

**Comment by fox-se** [comment]
> Спасибо за информацию. На первый взгляд вывод `ps` вписывается в работу скрипта.
> Вы пробовали решать проблему по шагам, как описано в вики? https://github.com/rvalitov/zabbix-php-fpm/wiki/Testing-and-Troubleshooting#2-the-template-does-not-work
> 
> Я так понимаю что пул автоопределяется, поэтому вероятно вы можете сразу приступить к этому пункту https://github.com/rvalitov/zabbix-php-fpm/wiki/Testing-and-Troubleshooting#2-get-status-of-required-pool
> 
> Сообщите о результатах.
# zabbix_get -s 127.0.0.1 -p 10050 -k php-fpm.status["/var/www/php-fpm/user_isp.sock","/php-fpm-status"]
{"pool":"user_isp","process manager":"dynamic","start time":1586862002,"start since":134,"accepted conn":5,"listen queue":0,"max listen queue":0,"listen queue len":0,"idle processes":0,"active processes":1,"total processes":1,"max active processes":1,"max children reached":0,"slow requests":0}

**Comment by rvalitov** [comment]
Как видно, данные все передаются, следовательно на стороне скрипта ошибок нет. Тогда возможно что в самом интерфейсе Заббикса эти элементы выключились или не активные. Надо смотреть уже на их статус и ошибки в настройках хоста в Заббиксе.

**Comment by ttsrg** [comment]
> Работает !
> 
> [root@ssssss ~]# ps aux | grep "php"
> root 910 0.0 0.5 363536 11072 ? Ss Apr11 0:11 php-fpm: master process (/etc/php-fpm.conf)
> apache 1034 0.2 0.9 370868 18396 ? S Apr11 10:14 php-fpm: pool www
> apache 1035 0.2 1.4 379076 26544 ? S Apr11 9:55 php-fpm: pool www
> apache 1036 0.2 1.0 372640 19968 ? S Apr11 10:11 php-fpm: pool www

Нет, думаю, что  проверять нужно  так на хосте :  
zabbix_agentd -t proc.num[php-fpm]
zabbix_agentd -t proc.num[php-fpm7.3]
я думаю, что корректый результат выдаст последний вариант.....

php из ppa:ondrej/php
тестировалось на ubuntu 16-18 , Zabbix 5

**Comment by fox-se** [comment]
[root@xxxx ~]# zabbix_agentd -t proc.num[php-fpm]
proc.num[php-fpm]                             [u|26]
[root@xxxx ~]# zabbix_agentd -t proc.num[php-fpm7.3]
proc.num[php-fpm7.3]                          [u|0]

Ваш скрипт начал работать с настройками, которые я выше указал.
Я его настраивал параллельно с другими шаблонами, не сразу пошел. Может и еще какие-то настройки повлияли.
Спасибо за отличный скрипт!

**Comment by ttsrg** [comment]
> [root@xxxx ~]# zabbix_agentd -t proc.num[php-fpm]
> **proc.num[php-fpm] [u|26]**
> [root@xxxx ~]# zabbix_agentd -t proc.num[php-fpm7.3]
> proc.num[php-fpm7.3] [u|0]
> 
> Ваш скрипт начал работать с настройками, которые я выше указал.
те надо все под рута делать?

**Comment by rvalitov** [comment]
Я запутался в этой переписке. Поясните пожалуйста.

> zabbix_agentd -t proc.num[php-fpm]
> zabbix_agentd -t proc.num[php-fpm7.3]
Какая цель в запуске этих команд, если мой скрипт не использует такого рода вызовы?

> Ваш скрипт начал работать с настройками, которые я выше указал.
Что именно и где вы поменяли? Я бы добавил этот кейс в вики.

**Comment by rvalitov** [comment]
@ttsrg 
если у вас не идентичная проблема, то прошу создать отдельный issue, чтобы в этом разобраться. Я лично тестировал на разных Debian, это не Ubuntu, но близко. Будем разбираться.

**Comment by fox-se** [comment]
Centos 7, Zabbix 4.4.6
Сейчас работает с этими настройками:
/etc/zabbix/zabbix_agentd.d/userparameter_php_fpm.conf
UserParameter=php-fpm.discover[*],sudo /etc/zabbix/zabbix_php_fpm_discovery.sh $1
UserParameter=php-fpm.status[*],/etc/zabbix/zabbix_php_fpm_status.sh $1 $2

/etc/zabbix/zabbix_server.conf
LogFile=/var/log/zabbix/zabbix_server.log
LogFileSize=0
PidFile=/var/run/zabbix/zabbix_server.pid
SocketDir=/var/run/zabbix
DBName=zabbix
DBUser=zabbix
DBPassword=xxxxxxxxxxxxxxxxxxxxxxx
SNMPTrapperFile=/var/log/snmptrap/snmptrap.log
Timeout=13
AlertScriptsPath=/usr/lib/zabbix/alertscripts
ExternalScripts=/usr/lib/zabbix/externalscripts
LogSlowQueries=3000
StatsAllowedIP=127.0.0.1

/etc/zabbix/zabbix_agentd.conf
PidFile=/var/run/zabbix/zabbix_agentd.pid
LogFile=/var/log/zabbix/zabbix_agentd.log
LogFileSize=0
Server=127.0.0.1
ServerActive=127.0.0.1
Hostname=Zabbix server
Timeout=12
AllowRoot=1
User=root
Include=/etc/zabbix/zabbix_agentd.d/*.conf

/etc/systemd/system/zabbix-agent.service.d/override.conf
[Service]
User=root
Group=root

root:root rwxr-xr-x  /etc/zabbix/zabbix_php_fpm_discovery.sh
root:root rwxr-xr-x  /etc/zabbix/zabbix_php_fpm_status.sh

# systemctl daemon-reload
# systemctl restart zabbix-agent

**Comment by rvalitov** [comment]
@fox-se спасибо за ответ. Не заметил отличий от инструкций, описанных в вики. Вы что-то добавляли свое, чего не было в вики?

**Comment by ttsrg** [comment]
> @ttsrg
> если у вас не идентичная проблема, то прошу создать отдельный issue, чтобы в этом разобраться. Я лично тестировал на разных Debian, это не Ubuntu, но близко. Будем разбираться.

Да оформил, отдельное спасибо за этот репо, интересные идеи реализованы, дебаг понравился. Есть предложения  расширить немного функционал, предложил бы в личку перейти

**Comment by fox-se** [comment]
> @fox-se спасибо за ответ. Не заметил отличий от инструкций, описанных в вики. Вы что-то добавляли свое, чего не было в вики?

Сначала ваш шаблон полностью не заработал, я не стал тратить время и переключился на другие, для шаблона Template DB MySQL (родной) добавил:
/etc/zabbix/zabbix_agentd.conf
AllowRoot=1
User=root

/etc/systemd/system/zabbix-agent.service.d/override.conf
[Service]
User=root
Group=root

и заработали оба! Что повлияло из предыдущих настроек я не знаю.

**Comment by rvalitov** [comment]
@fox-se понятно, спасибо. Все изменения, о которых вы говорили, уже описаны в инструкции по установке этого шаблона https://github.com/rvalitov/zabbix-php-fpm/wiki/Installation
Если возникли где-то сложности или что-то оказалось там не понятным, пожалуйста, дайте знать - я обновлю мануал. Рад, что в итоге всё работает!
