### ISSUE TITLE
не отрабатывает ключ [php-fpm] 

### ISSUE THREAD

**Issue by ttsrg** [rvalitov/zabbix-php-fpm#30]
Добрый день. 
В нескольких темплейтах сталкиваюсь с ошибкой, пока не разобрался, если используется ключ [php-fpm] , то зажигаются все тригеры, которые его используют.
проверить можно на хосте: zabbix_agentd -t proc.num[php-fpm]
[u|0] - выхлоп,  0 это ошибка, должно показывать кол-во процессов

в моем случае работает костыль, если я перепрописываю ключ
zabbix_agentd -t proc.num[php-fpm7.3]

php  7.3 и 7.4 из ppa:ondrej/php либо дефолтные 7.0,7.2
тестировалось на ubuntu 16.04 и 18.04 , Zabbix 5

Альтернативы не помогли, решения пока не нашел

**Comment by rvalitov** [comment]
Спасибо, посмотрю.

**Comment by rvalitov** [comment]
В моем скрипте и шаблоне такой ключ не используется. Следовательно, такая проблема здесь не возникает. Относительно других шаблонов - это их недоработки, рекомендую обратиться в их тех.поддержку.
