### ISSUE TITLE
Problems to retrieve php-fpm data

### ISSUE THREAD

**Issue by paydaycay** [rvalitov/zabbix-php-fpm#34]
Hi, I succeeded to install everything thanks to your awesome explanations in the Wiki.

Unfortunatly, I can't retrieve a lot of php-fpm data like php-fpm.cpu, php-fpm.max_active_processes, etc..

If I try to run it with zabbix_get I can see it's an unsupported item key.

If we take a look in the userparameter_php_fpm.conf, we can see that there isn't any UserParameter for all theses commands. 

So, how do you make it work ? Did I miss something ?

**Comment by rvalitov** [comment]
Parameters like CPU usage is retrieved using standard built-in native functions of Zabbix. That's why there's no need to specify them inside UserParameter. What version of Zabbix agent do you use? Do you use it in some special potentially limited environment like Raspberry PI?

**Comment by paydaycay** [comment]
Oops sorry, php-fpm.cpu works but I can't get a lot of other values (php-fpm.slow_requests, php-fpm.active_processes, php-fpm.accepted_conn, php-fpm.idle_processes, php-fpm.listen_queue, etc...).
Zabbix agent version is 4.4.9 and OS is Ubuntu 16.04. I don't use any limited environment.

**Comment by rvalitov** [comment]
Did you test what data actually is reported by PHP? Can you open the status page from the server?

**Comment by paydaycay** [comment]
Yes here is what I retrieve from status page : 
`curl -L 127.0.0.1/php-fpm-status
pool:                 www
process manager:      dynamic
start time:           18/Jun/2020:02:00:13 +0200
start since:          23873
accepted conn:        17289
listen queue:         0
max listen queue:     0
listen queue len:     0
idle processes:       2
active processes:     1
total processes:      3
max active processes: 4
max children reached: 0
slow requests:        0`

What I retrieve from zabbix_get : 
`zabbix_get -s IP_HOST_FPM -k php-fpm.active_processes[/run/php/php7.2-fpm.sock]
ZBX_NOTSUPPORTED: Unsupported item key.`

Here what I have in Zabbix for my pool : 

![image](https://user-images.githubusercontent.com/8417078/84987328-385f1480-b140-11ea-874c-30a440c2b179.png)

And for PHP-FPM : 

![image](https://user-images.githubusercontent.com/8417078/84987455-72c8b180-b140-11ea-8c11-8c00840b4275.png)

**Comment by rvalitov** [comment]
Thank you! I see that the the call to get items is wrong. It must be as follow, [see Wiki](https://github.com/rvalitov/zabbix-php-fpm/wiki/Testing-and-Troubleshooting#2-get-status-of-required-pool):
```
zabbix_get -s ZABBIX_HOST_IP -p ZABBIX_HOST_PORT -k php-fpm.discover.status["POOL_URL","POOL_PATH"]
```

In your case a test call will be (if the path is default as suggested in the Wiki):

```
zabbix_get -s IP_HOST_FPM -k php-fpm.active_processes["/run/php/php7.2-fpm.sock","/php-fpm-status"]
```

Is this call working properly?

**Comment by paydaycay** [comment]
ok @rvalitov Thank you for your help :)

**Comment by rvalitov** [comment]
I published a new release, can you test it please? You need to update the file `userparameter_php_fpm.conf`.
There was a problem with sudo access rights to the status script. I also updated the the Wiki, see section https://github.com/rvalitov/zabbix-php-fpm/wiki/Installation#13-root-privileges Please follow the instructions there. Thank you!

**Comment by rvalitov** [comment]
/remind me this issue in 10 days
