### ISSUE TITLE
Pools with same name are mixed up

### ISSUE THREAD

**Issue by rieschl** [rvalitov/zabbix-php-fpm#35]
Hi! I just installed the template and it's working quite well. Thank you for your efforts!

One thing I noticed is, that the discovery script has problems to distinguish the pools from different PHP versions.
I have PHP7.3 and PHP7.4 installed, both having a `prod` and `dev` pool.
The script seems to pick the first pool name it discovers and dismisses other pools from other PHP versions.
My system is Debian 10, PHP is installed with deb.sury.org repo.

At first glance I don't know if it's even possible to distinguish those. Maybe with the socket name?
I'd rather not rename the pools to be unique.

Thanks for your help!

**Comment by rieschl** [comment]
Hm, it's probably a good way to name each pool unique. For new setups I'll definitely consider that. But on existing servers it's a bit cumbersome to change pools, because of multiple places where I use it.
In my setups I use the `$pool` variable to set the socket:
`listen = /run/php/php7.4-fpm-$pool.sock`
So I have to change that in Apache in the proxy_fcgi_module configs, too.

Afaik the socket (or ip) should already be unique, so maybe the pool name itself isn't even required.

**Comment by rvalitov** [comment]
@rieschl a new PR is ready and published. Can you please test it and confirm that it works? For the test it's enough to update just the single file `zabbix_php_fpm_discovery.sh` on your machine. Thank you!

**Comment by rvalitov** [comment]
/remind me this issue in 10 days
