### ISSUE TITLE
Wiki changes needed

### ISSUE THREAD

**Issue by FL0od13** [rvalitov/zabbix-php-fpm#36]
Hi!
I installed your solution on Zabbix 5.0.1
It's works, but wiki needs corrections.

1) Installation 1.3.2

_Add the following line to this file:
zabbix ALL = NOPASSWD: /etc/zabbix/zabbix_php_fpm_discovery.sh_

**Replace for:**

_Add the following lines to this file:
zabbix ALL = NOPASSWD: /etc/zabbix/zabbix_php_fpm_discovery.sh
zabbix ALL = NOPASSWD: /etc/zabbix/zabbix_php_fpm_status.sh_

And

_Now edit the file /etc/zabbix/zabbix_agentd.d/userparameter_php_fpm.conf. Find the line:
UserParameter=php-fpm.discover[*],/etc/zabbix/zabbix_php_fpm_discovery.sh $1
Add sudo there, so the line should be:
UserParameter=php-fpm.discover[*],sudo /etc/zabbix/zabbix_php_fpm_discovery.sh $1_

**Replace for:**

_Now edit the file /etc/zabbix/zabbix_agentd.d/userparameter_php_fpm.conf. Find the lines:
UserParameter=php-fpm.discover[*],/etc/zabbix/zabbix_php_fpm_discovery.sh $1
UserParameter=php-fpm.status[*],/etc/zabbix/zabbix_php_fpm_status.sh $1 $2
Add sudo there, so the lines should be:
UserParameter=php-fpm.discover[*],sudo /etc/zabbix/zabbix_php_fpm_discovery.sh $1
UserParameter=php-fpm.status[*],sudo /etc/zabbix/zabbix_php_fpm_status.sh $1 $2_

2) Testing 2.2

_Command syntax:
zabbix_get -s ZABBIX_HOST_IP -p ZABBIX_HOST_PORT -k php-fpm.discover.status["POOL_URL","POOL_PATH"]_

**Replace for:**

_Command syntax:
zabbix_get -s ZABBIX_HOST_IP -p ZABBIX_HOST_PORT -k php-fpm.status["POOL_URL","POOL_PATH"]_

Thank you!

**Comment by rvalitov** [comment]
Thank you very much! I hope I will soon try out myself the Zabbix 5 #33 and will make the required updates.

**Comment by rvalitov** [comment]
I believe the `sudo` part of your comments are related to #32 and it was fixed in the latest release. Now the `userparameter_php_fpm.conf` file contains the `sudo` word in them by default, so no need to edit this file anymore.  Your part of code:
```
zabbix ALL = NOPASSWD: /etc/zabbix/zabbix_php_fpm_discovery.sh
zabbix ALL = NOPASSWD: /etc/zabbix/zabbix_php_fpm_status.sh
```
I changed to:
```
zabbix ALL = NOPASSWD: /etc/zabbix/zabbix_php_fpm_discovery.sh,/etc/zabbix/zabbix_php_fpm_status.sh
```
This syntax should be valid, can you please confirm that it works in your case?
There was a typo in syntax for `zabbix_get`, thank you for finding this, Wiki fixed.

P.S. I also tested template with Zabbix 5.0.1 and it works.

**Comment by FL0od13** [comment]
_>>This syntax should be valid, can you please confirm that it works in your case?_

Yes, this syntax also works.

Thank you!

**Comment by rvalitov** [comment]
Great, thank you! I'm closing this issue then.
