### ISSUE TITLE
Discovery problem in LXD/LXC container (lsof and zabbix user)

### ISSUE THREAD

**Issue by alepaes1975** [rvalitov/zabbix-php-fpm#40]
Hi,

With root, zabbix_php_fpm_discovery.sh running ok. But with:

sudo -u zabbix /etc/zabbix/zabbix_php_fpm_discovery.sh debug returns permission denied:

root@intranet:/etc/zabbix# sudo -u zabbix ./zabbix_php_fpm_discovery.sh debug
Debug mode enabled
Current user is zabbix
Status path to be used: /php-fpm-status
Local directory is .
Helper script ./zabbix_php_fpm_status.sh is reachable
Reading cache file ./php_fpm.cache...
Started analysis of pool www, PID 68372
Error: failed to get process information. Probably insufficient privileges. Use sudo or run this script under root.
Error: failed to discover information for pool www

Debugging the script with bash -x, I see that inside the container, lsof returns nothing about this pid (with zabbix or www-data):

root@intranet:/etc/zabbix# sudo -u zabbix /usr/bin/lsof -P -p 68372 | grep -e "TCP"

root@intranet:/etc/zabbix# sudo -u www-data /usr/bin/lsof -P -p 68372 | grep -e "TCP"

root is OK:
root@intranet:/etc/zabbix# /usr/bin/lsof -P -p 68372 | grep -e "TCP"
php-fpm7. 68372 www-data    9u  IPv4 2949942      0t0     TCP localhost:9000 (LISTEN)

I put lsof in /etc/sudoers, but I think the problem is about /proc in LXC. I don't want to run zabbix_agentd2 as root.

Congrats about the scripts and template. One of the best in documentation !

**Comment by rvalitov** [comment]
Hello! It seems you have a mistake in your call syntax. The script must be run with `sudo` that is missing in your case. A correct call would be:
```
sudo -u zabbix sudo /etc/zabbix/zabbix_php_fpm_discovery.sh debug
```

A first `sudo` here is used to run the command as `zabbix` user, the second `sudo` is run by `zabbix` user to run the script with root privileges.

You don't need to put `lsof` to sudoers or run the zabbix agent as root. All you need to do is to follow the [permissions setup section](https://github.com/rvalitov/zabbix-php-fpm/wiki/Installation#13-root-privileges) of the Wiki. It describes how to run zabbix agent without root but to allow it to run only specified scripts with `sudo`. Besides, it's not effective way to test the script the way you do it. Using `zabbix-get` it's much more efficient, it's also described in the Wiki.

Thank you and waiting for your feedback.

**Comment by rvalitov** [comment]
In the Wiki I see lots of outdated examples with `root`, I will update their syntax to run as a standard user.

**Comment by rvalitov** [comment]
@alepaes1975 I have updated the examples in the Wiki, I hope this can avoid any misunderstanding. Please, kindly provide your feedback if your issue is resolved. Thank you!

**Comment by alepaes1975** [comment]
![image](https://user-images.githubusercontent.com/67766108/86479588-d3501500-bd22-11ea-848b-a67c25e74541.png)

Hi @rvalitov,

Everthing is ok now, thank you very much !!!

**Comment by rvalitov** [comment]
You're welcome! Enjoy the template! 😊
