### ISSUE TITLE
How to manually setup nginx in ISPConfig if not using the patch

### ISSUE THREAD

**Issue by wfilho** [rvalitov/zabbix-php-fpm#47]
I've read the Wiki, but I couldn't find how to setup nginx file when I need to install it without using the PATCH.

I followed the instructions but as we can't modify the files using the patch, I've had to search for nginx how-tos to get the Status Page working.

On the web, there nothing about it with ISPConfig. Thanks in advance for your help !!

Problem:

I’m getting a blank page instead of status page.
Nothing wrong on access.log its show that the page was requested
Nothing on error.log with the followed nginx setup:

=============================
/etc/nginx/sites-available/default:

 ```
location = /php-fpm-status {
    # access_log off;
    allow 127.0.0.1;
    # deny all;
    include fastcgi_params;
    fastcgi_index index.php;
    # fastcgi_pass 127.0.0.1:9000;
    fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }
```
============================================
When I insert this line:

`fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;`

I start to get an error on error.log:

`2020/07/23 21:50:24 [error] 11585#11585: *71685 FastCGI sent in stderr: “Access to the script ‘/usr/share/nginx/html/php-fpm-status’ has been denied (see security.limit_extensions)” while reading response header from upstream, client: 127.0.0.1, server: _, request: “GET /php-fpm-status HTTP/1.1”, upstream: “fastcgi://unix:/run/php/php7.0-fpm.sock:”, host: “127.0.0.1”`

Thanks for your help and for sharing your knowledge.

Regards.

**Comment by wfilho** [comment]
I managed to make it work, just don't know if it's the correct way to do with ispconfig manually and if it will be overwritten when I save something on the ISPConfig Page.

Fist of all, I was putting the location code without the spaces in the beginning to move it inside the main block. Sorry, I don't know nginx configuration ;(

Then, using the following code, inside the /etc/nginx/sites-available/default I could access the status page with `http://127.0.0.1/php-fpm-status`

```
        location ~ ^/(php-fpm-status|status|ping)$ {
                access_log off;
                #allow 127.0.0.1;
                #allow 1.2.3.4#your-ip;
                #deny all;
                include /etc/nginx/fastcgi_params;
                #fastcgi_pass unix:/var/lib/php7.0-fpm/web1.sock;
                fastcgi_pass unix:/var/lib/php7.0-fpm/web1.sock;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
```

It will be interesting to know the correct way to do it if you can help and insert it in the wiki would be greate !

Thanks in advance.

Regards.

**Comment by rvalitov** [comment]
Thank you very much for your comments and proposal of the solution. I have installed `nginx` to my sandbox and making some tests. I will come back to you soon.

**Comment by rvalitov** [comment]
@wfilho 
Wiki updated, thank you so much for pointing out that instructions for NGINX were missing.
I also created and added a special patch for NGINX configuration file in ISPConfig.
