### ISSUE TITLE
Не отдает на сервер данные 

### ISSUE THREAD

**Issue by conter86** [rvalitov/zabbix-php-fpm#53]
При запросе 
`curl localhost/php-fpm-status

pool:                 www
process manager:      dynamic
start time:           30/Aug/2020:17:40:46 +0300
start since:          3244
accepted conn:        2760
listen queue:         0
max listen queue:     0
listen queue len:     0
idle processes:       5
active processes:     1
total processes:      6
max active processes: 9
max children reached: 0
slow requests:        0`

`zabbix_agent2 -t web.page.get[localhost,/php-fpm-status,80]
web.page.get[localhost,/php-fpm-status,80]    [s|HTTP/1.1 200 OK
Connection: close
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
Content-Type: text/plain;charset=UTF-8
Date: Sun, 30 Aug 2020 15:36:44 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Server: nginx/1.14.2

pool:                 www
process manager:      dynamic
start time:           30/Aug/2020:17:40:46 +0300
start since:          3357
accepted conn:        2859
listen queue:         0
max listen queue:     0
listen queue len:     0
idle processes:       3
active processes:     3
total processes:      6
max active processes: 13
max children reached: 0
slow requests:        0
`
донные получает а на сервере они не появляются помогите что я сделал не так 
![2020-08-30](https://user-images.githubusercontent.com/22930642/91663197-185cb180-eaf0-11ea-94f5-90da55d48407.png)

**Comment by rvalitov** [comment]
Добрый день! Вы пробовали следовать тому, что написано в вики, в частности https://github.com/rvalitov/zabbix-php-fpm/wiki/Testing-and-Troubleshooting ?

**Comment by conter86** [comment]
Вот что он выдает 


`sudo bash /etc/zabbix/zabbix_php_fpm_discovery.sh POOL_PATH
{"data":[]}root@koktebel:~# `



`sudo -u zabbix sudo /etc/zabbix/zabbix_php_fpm_discovery.sh POOL_PATH debug
Debug mode enabled
Current user is root
Status path to be used: /php-fpm-status
Local directory is /etc/zabbix
Helper script /etc/zabbix/zabbix_php_fpm_status.sh is reachable
Reading cache file /etc/zabbix/php_fpm.cache...
Started analysis of pool www, PID 155143
Checking process: php-fpm7. 155143 www-data    5u  IPv4           50105436      0t0      TCP koktebel:51206->192.168.89.252:11211 (ESTABLISHED)
Warning: expected connection state must be LISTEN, but it was not detected
Checking process: php-fpm7. 155143 www-data    6u  IPv4           50105713      0t0      TCP koktebel:51768->192.168.89.252:11211 (ESTABLISHED)
Warning: expected connection state must be LISTEN, but it was not detected
Checking process: php-fpm7. 155143 www-data    9u  unix 0x000000007b2ac549      0t0 40214252 /run/php/php7.4-fpm.sock type=STREAM
Found socket /run/php/php7.4-fpm.sock
Failed to get status for pool www, socket /run/php/php7.4-fpm.sock, status path /php-fpm-status
Status script returned: Utility 'cgi-fcgi' not found. Please, install it first.
Error: socket /run/php/php7.4-fpm.sock didn't return valid data
Error: failed to discover information for pool www
Processing pools from old cache...
Saving new cache file /etc/zabbix/php_fpm.cache...
Resulting JSON data for Zabbix:
{"data":[]}root@koktebel:~# `


`sudo ps aux | grep "php-fpm"
root        2516  0.0  0.1 255448  5192 ?        Ss   Aug31   0:08 php-fpm: master process (/etc/php/7.4/fpm/php-fpm.conf)
www-data  155143  0.0  3.4 367428 108056 ?       S    19:36   0:13 php-fpm: pool www
www-data  155144  0.0  3.5 370788 111896 ?       S    19:36   0:12 php-fpm: pool www
www-data  155145  0.0  4.2 391632 132756 ?       R    19:36   0:13 php-fpm: pool www
www-data  155154  0.0  3.1 360668 100440 ?       S    19:36   0:13 php-fpm: pool www
www-data  155155  0.0  4.3 399048 136604 ?       R    19:36   0:11 php-fpm: pool www
www-data  155161  0.0  2.9 354464 94248 ?        S    19:36   0:10 php-fpm: pool www
root      155754  0.0  0.0   3080   832 pts/0    S+   19:40   0:00 grep php-fpm
root@koktebel:~# `



Есть вопрос а почему он пытается искать в unix:/var/lib/php7.3-fpm/web1.sock; когда он unix:/run/php/php7.4-fpm.sock

**Comment by rvalitov** [comment]
Во-первых не установлена утилита 'cgi-fcgi'. В вики написано какие зависимости требуются и порядок установки. Во-вторых проверьте, настроили ли вы всё правильно в плане sudo прав для скрипта. В вики тоже это есть.

Насчет `unix:/var/lib/php7.3-fpm/web1.sock` - на основе чего вы сделали такое заключение? В предоставленном вами логе везде стоит `php7.4`.

**Comment by conter86** [comment]
cgi-fcgi я как понимаю это компонент от Apache2 ?
У меня не стоит Apache2  у меня развернут nginx и как мне быть в таком случаи ?

**Comment by rvalitov** [comment]
нет, это отдельная утилита, никак не связана с Apache

**Comment by conter86** [comment]
Я в поиске искал ссылается на apahce 2
 Не могли помочь как ее поставить или ссылку на установку или команды дать

**Comment by rvalitov** [comment]
Всё расписано в Вики, все нужные зависимости от каждую ОС https://github.com/rvalitov/zabbix-php-fpm/wiki/Installation#11-install-prerequisites

**Comment by conter86** [comment]
root@koktebel:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by conter86** [comment]
root@koktebel:~# sudo bash /etc/zabbix/zabbix_php_fpm_discovery.sh POOL_PATH
{"data":[{"{#POOLNAME}":"www","{#POOLSOCKET}":"/run/php/php7.4-fpm.sock"}]}root@koktebel:~# 
root@koktebel:~# 
root@koktebel:~# 
root@koktebel:~# 
L_PATH debugl:~# sudo -u zabbix sudo /etc/zabbix/zabbix_php_fpm_discovery.sh POOL
Debug mode enabled
Current user is root
Status path to be used: /php-fpm-status
Local directory is /etc/zabbix
Helper script /etc/zabbix/zabbix_php_fpm_status.sh is reachable
Reading cache file /etc/zabbix/php_fpm.cache...
Started analysis of pool www, PID 456397
Checking process: php-fpm7. 456397 www-data    4u  IPv4           67891963      0t0      TCP koktebel:52426->192.168.89.251:3306 (ESTABLISHED)
Warning: expected connection state must be LISTEN, but it was not detected
Checking process: php-fpm7. 456397 www-data    5u  IPv4           67885648      0t0      TCP koktebel:34738->192.168.89.252:11211 (ESTABLISHED)
Warning: expected connection state must be LISTEN, but it was not detected
Checking process: php-fpm7. 456397 www-data    6u  IPv4           67885617      0t0      TCP koktebel:34682->192.168.89.252:11211 (ESTABLISHED)
Warning: expected connection state must be LISTEN, but it was not detected
Checking process: php-fpm7. 456397 www-data    7u  IPv4           67967430      0t0      TCP koktebel:40990->static-ip-18.189.195-137.feonet.net:80 (SYN_SENT)
Warning: expected connection state must be LISTEN, but it was not detected
Checking process: php-fpm7. 456397 www-data    9u  unix 0x0000000091162498      0t0 54895940 /run/php/php7.4-fpm.sock type=STREAM
Found socket /run/php/php7.4-fpm.sock
Status data for pool www, socket /run/php/php7.4-fpm.sock, status path /php-fpm-status is valid
Detected pool's process manager is NOT ondemand, it will not be cached
Success: socket /run/php/php7.4-fpm.sock returned valid status data
Processing pools from old cache...
Saving new cache file /etc/zabbix/php_fpm.cache...
Resulting JSON data for Zabbix:
{"data":[{"{#POOLNAME}":"www","{#POOLSOCKET}":"/run/php/php7.4-fpm.sock"}]}root@koktebel:~#

**Comment by conter86** [comment]
![2020-09-04](https://user-images.githubusercontent.com/22930642/92214976-cc698e00-ee9c-11ea-9977-7f912fd5902f.png)

**Comment by conter86** [comment]
Надо было становит  sudo apt-get install libfcgi0ldbl 
А по запросу cgi-fcgi в поиске выдавал что угодно кроме того что надо

**Comment by rvalitov** [comment]
Вопрос решен? Как я могу улучшить этот проект? Какой информации вам было недостаточно в вики?

**Comment by conter86** [comment]
![2020-09-04 (1)](https://user-images.githubusercontent.com/22930642/92217889-f8870e00-eea0-11ea-8c47-ba1f1f16bab5.png)
А почему не может получить в се данные ?
```
Preprocessing failed for:
1. Failed: cannot extract value from json by path "$['listen queue len']"
```

**Comment by rvalitov** [comment]
Обнаружение пула у вас работает. Это хорошо. Осталось теперь разобраться с получением данных. Прошу опять обратиться к Вики параграф о тестировании получения данных с помощью `zabbix_get` https://github.com/rvalitov/zabbix-php-fpm/wiki/Testing-and-Troubleshooting#22-test-with-zabbix_get

**Comment by conter86** [comment]
root@koktebel:~# zabbix_get -s 127.0.0.1 -p 10050 -k php-fpm.discover["/php-fpm-status"]
zabbix_get [472400]: Check access restrictions in Zabbix agent configuration

я что-то не пойму как правильно сделать запрос

**Comment by rvalitov** [comment]
Прошу вас не редактировать свое существующее сообщение, а писать новое, иначе я не получаю уведомлений о новых событиях в этой теме и просто не заглядываю сюда.

Сообщение `Check access restrictions in Zabbix agent configuration` означает, что агенту не хватает прав. Вы полностью следовали инструкции по установке скрипта, описанной в Вики? Все шаги выполнили?

**Comment by conter86** [comment]
Я как по инструкции добавил в /etc/sudoers  строчку zabbix ALL = NOPASSWD: /etc/zabbix/zabbix_php_fpm_discovery.sh,/etc/zabbix/zabbix_php_fpm_status.sh и перезагрузил контейнер 
Команда id -u выводит root@koktebel:~# id -u
0

**Comment by rvalitov** [comment]
Если погуглить, то выходит такая ссылка https://www.zabbix.com/forum/zabbix-help/50557-check-access-restrictions-in-zabbix-agent-configuration-error
Из этого следует, что ошибка не связана со скриптом, а связана в неправильной настройке конфигурационного файла Zabbix agent. Проверьте, что у вас стоят корректные значения в поле Server и ServerActive, что указанные IP адреса доступны (например через ping, telnet). А также проверьте что у вас корректно работает служба DNS. Например, бывает так, что 127.0.0.1 отрабатывает, а localhost нет. И бывает еще проблемы с неверной настройкой IPv6, когда например localhost идентифицируется по IPv6 адресу, что приводит к тому, что некоторые сервисы не работают корректно. Я рекомендую везде в настройках Zabbix прописывать IP адреса, а не имена доменов. Если Zabbix Agent и Zabbix Server расположены на разных серверах или контейнерах, то проверьте что они могут обмениваться данными по сети друг с другом. Возможно файрволом где-то закрыт какой-то из нужных портов, или какой-то из IP адресов Zabbix агента или сервера не имеет разрешений для доступа.
