### ISSUE TITLE
template has 1 item

### ISSUE THREAD

**Issue by nbatien069** [rvalitov/zabbix-php-fpm#59]
HI, I imported successfully but I just see 1 item 
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/41286032/115206510-de92f680-a124-11eb-8d09-0d690ce945f0.png">
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/41286032/115206578-f10d3000-a124-11eb-9c98-181de743ad27.png">

**Comment by nbatien069** [comment]
I use Zabbix 5.0.10

**Comment by rvalitov** [comment]
@nbatien069 Hi! Did you follow the Troubleshooting guide link posted in the previous message by bot?
If the problem still happens, please, describe what steps exactly you followed from the guide and what results did you get.
