### ISSUE TITLE
doesn't work with listen on IP

### ISSUE THREAD

**Issue by pbousek** [rvalitov/zabbix-php-fpm#8]
Hello, it's probably don't work when pool listen on localhost:port

lsof of process will show that it listen on port, but discovery wont detect it.

php-fpm7. 1110 defualt    0u  IPv4  15760      0t0    TCP localhost:8002 (LISTEN)

Could I kindly ask you for this possibility?
Thanks

Petr

**Comment by rvalitov** [comment]
Hello! Thank you for reporting this. Yes, indeed, this code works only with sockets. I will try to improve this.

**Comment by pbousek** [comment]
Hello, I found that when you use "TCP" instead of "unix" in the following line works well
        POOL_SOCKET=`$S_LSOF -p $POOL_PID 2>/dev/null | $S_GREP TCP | $S_HEAD -1 | $S_AWK '{ print $(NF-1)}'`

Both shell scripts return what they should return, but template doesn't show nothing except number of cpu, as I  mentioned in issue related to zabbix 4.4 template porting.

**Comment by rvalitov** [comment]
Ok, thank you for this investigation. I will check that.

**Comment by pbousek** [comment]
and maybe you can mention in readme that cgi-fcgi binary is in package libfcgi-bin in debian stable

**Comment by rvalitov** [comment]
cgi-fcgi is a part of [libfcgi0ldbl](https://packages.debian.org/buster/libfcgi0ldbl) and that was already specified in the README in the prerequisites section.

**Comment by rvalitov** [comment]
Now the listen on IP should work, if not, then please, let me know here.

**Comment by LeoShivas** [comment]
Can someone test this in https://github.com/rvalitov/zabbix-php-fpm/pull/9# :
 POOL_SOCKET=`$S_LSOF -p $POOL_PID 2>/dev/null | $S_GREP -E "unix|TCP" | $S_HEAD -1 | $S_AWK '{ print $9}'`
?

**Comment by pbousek** [comment]
> cgi-fcgi is a part of [libfcgi0ldbl](https://packages.debian.org/buster/libfcgi0ldbl) and that was already specified in the README in the prerequisites section.

I'm afraid that you are not right https://packages.debian.org/search?searchon=contents&keywords=cgi-fcgi&mode=path&suite=stable&arch=any 
libfcgi0ldbl only contain som libraries .. I did everything exactly like you have in README, but cgi-fcgi binary was not installed, fixed after installation of libfcgi-bin

**Comment by rvalitov** [comment]
@pbousek thank you for the details! I have updated the README.
